### ISSUE TITLE
Storing the salience graph

### ISSUE THREAD

**Issue by farskipper** [farskipper/pico-engine-node-prototype#1]
Currently I implement the salience graph by storing it in the process memory. I'm thinking every pico-engine process will each install the rulesets into their process.

As part of installing/uninstalling a ruleset it will update the salience graph. Since rule-sets don't change regularly, the graph will be mostly read only.

When a KRL rule is parsed and compiled I store a tree with the known event domain and types.
`domain` -> `type`
If a domain or type is unknown it leaves it keys a blank string.

The salience graph is structured lie this.
`domain` -> `type` -> `rid` -> `rule_name`

It's straight forward how the graph is updated when rules are installed/uninstalled. It simply reads the rules graph `domain` -> `type` and indexes it in the salience graph along with it's rid and rule_name. It also stores blank keys if a domain or type is unknown.

When an event comes in, we look in the salience graph to know which rules to evaluate. For example an event with domain `D` and type `T`. We'll look at the following paths:

`'D'` -> `'T'`
`''` -> `'T'`
`'D'` -> `''`
`''` -> `''`

From each path it collects the unique list of rules it that match. Thus, only the rules that could possible fire on a given event will be selected.

**Comment by windley** [comment]
Why would a domain or type be unknown?

**Comment by farskipper** [comment]
We'll always know the domain and type of the event being processed. However, some rules don't know exactly which domain or type they will fire on. i.e.
```
select when pageview re#...#
```
We know the domain, but not the type. So when that rule get's registered it is put in the graph as `'pageview'` -> `''` so when any event comes in with domain `'pageview'`, it will evaluate that rules event expression.

**Comment by windley** [comment]
This was a historical situation. When the domain was unspecified, it was assumed to be 'web' 

I think for KRLv2 we can lose that and ensure that there's always a domain and a type.

**Comment by farskipper** [comment]
So the event expression syntax will require that there are always a domain and type explicitly defined?

Sweet! That will simplify things.

**Comment by windley** [comment]
I've made a note of it here: https://github.com/Picolab/pico-engine/issues/21

**Comment by farskipper** [comment]
Cool. I've committed the change for the simpler salience graph look-up.
