### ISSUE TITLE
Storing the state of a rules state machine

### ISSUE THREAD

**Issue by farskipper** [farskipper/pico-engine-node-prototype#2]
Currently I'm storing the state in the db. Storing it in process memory is problematic for scaling horizontally. Since an event A may come into machine 1, then event B come into machine 2. Thus, machine 2 will not know that event A already came.

It's trivial to change where we are storing the state. I just need a key and value. (the key is the pico instance id, the rule id and rule name)

Ultimately store it in memcache or redis so it can be shared between processes, but still be fast to access and easy to flush.

**Comment by windley** [comment]
Yeah, there's plenty of places where memcache comes in handy, this is one of them.
